### ISSUE TITLE
Error after trying build ..

### ISSUE THREAD

**Issue by Ridermansb** [kazupon/vue-plugin-boilerplate#4]
`$ npm run build`

```
> vue-gmaps@0.0.0-semantic-release build /Users/ridermansb/Projects/tmp/vue-gmaps
> node config/build.js && npm run docs:build

/Users/ridermansb/Projects/tmp/vue-gmaps/config/build.js:19
let entries = getAllEntries()
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by kciter** [comment]
Maybe updating the node version `>= 6.0` will fix it.
